spin_manifest_version = "1"
authors = ["Ryan Levick <me@ryanlevick.com>"]
description = "A todo application written in spin"
name = "todo"
trigger = { type = "http", base = "/api" }
version = "0.1.0"

[[component]]
id = "todo"
source = "target/wasm32-wasi/release/todo.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/todos/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
